Feature - Login view controller (UI).
josipas/QuizApp pull request #5
Opened 2022-07-08 08:03 UTC by josipas

https://user-images.githubusercontent.com/52414221/177946316-d410f32a-ff2b-448a-ad01-35735b98edb6.mp4

2022-07-08 08:45 UTC, istaudacher requested changes

2022-07-08 08:45 UTC, istaudacher commented on QuizApp/QuizApp/LoginViewController.swift
> +    private let gradient = CAGradientLayer()
newline below

2022-07-08 08:45 UTC, istaudacher commented on QuizApp/QuizApp/LoginViewController.swift
> +        let startColor = UIColor(red: 0.453, green: 0.308, blue: 0.637, alpha: 1).cgColor
Please extract creating gradient in separate private function.

2022-07-08 08:45 UTC, istaudacher commented on QuizApp/QuizApp/LoginViewController.swift
> +                loginButton.isEnabled = true
Please extract styling loginButton in separate functions:
* enableLoginButton
* disableLoginButton

2022-07-08 09:59 UTC, istaudacher approved these changes

2022-07-08 15:24 UTC, marinzg requested changes

2022-07-08 15:24 UTC, marinzg commented on QuizApp/QuizApp/LoginViewController.swift
> +        }
`{` goes into new line - [style guide](https://github.com/fiveagency/ios-swift-guide/tree/master/Code%20Style#if-else-statement)

2022-07-11 07:51 UTC, istaudacher approved these changes

2022-07-11 08:55 UTC, marinzg approved these changes

2022-07-11 09:19 UTC, merged